type Country = {
  code: string;
  [key: `name_${string}`]: string;
};

export const countries: Country[] = [
  { code: 'AF', name_en: 'Afghanistan', name_ja: 'アフガニスタン' },
  { code: 'AX', name_en: 'Aland Islands', name_ja: 'オーランド諸島' },
  { code: 'AL', name_en: 'Albania', name_ja: 'アルバニア' },
  { code: 'DZ', name_en: 'Algeria', name_ja: 'アルジェリア' },
  { code: 'AS', name_en: 'American Samoa', name_ja: 'アメリカ領サモア' },
  { code: 'AD', name_en: 'Andorra', name_ja: 'アンドラ' },
  { code: 'AO', name_en: 'Angola', name_ja: 'アンゴラ' },
  { code: 'AI', name_en: 'Anguilla', name_ja: 'アンギラ' },
  { code: 'AQ', name_en: 'Antarctica', name_ja: '南極' },
  {
    code: 'AG',
    name_en: 'Antigua And Barbuda',
    name_ja: 'アンティグア・バーブーダ',
  },
  { code: 'AR', name_en: 'Argentina', name_ja: 'アルゼンチン' },
  { code: 'AM', name_en: 'Armenia', name_ja: 'アルメニア' },
  { code: 'AW', name_en: 'Aruba', name_ja: 'アルバ' },
  { code: 'AU', name_en: 'Australia', name_ja: 'オーストラリア' },
  { code: 'AT', name_en: 'Austria', name_ja: 'オーストリア' },
  { code: 'AZ', name_en: 'Azerbaijan', name_ja: 'アゼルバイジャン' },
  { code: 'BS', name_en: 'Bahamas', name_ja: 'バハマ' },
  { code: 'BH', name_en: 'Bahrain', name_ja: 'バーレーン' },
  { code: 'BD', name_en: 'Bangladesh', name_ja: 'バングラデシュ' },
  { code: 'BB', name_en: 'Barbados', name_ja: 'バルバドス' },
  { code: 'BY', name_en: 'Belarus', name_ja: 'ベラルーシ' },
  { code: 'BE', name_en: 'Belgium', name_ja: 'ベルギー' },
  { code: 'BZ', name_en: 'Belize', name_ja: 'ベリーズ' },
  { code: 'BJ', name_en: 'Benin', name_ja: 'ベナン' },
  { code: 'BM', name_en: 'Bermuda', name_ja: 'バミューダ' },
  { code: 'BT', name_en: 'Bhutan', name_ja: 'ブータン' },
  { code: 'BO', name_en: 'Bolivia', name_ja: 'ボリビア' },
  {
    code: 'BA',
    name_en: 'Bosnia And Herzegovina',
    name_ja: 'ボスニア・ヘルツェゴビナ',
  },
  { code: 'BW', name_en: 'Botswana', name_ja: 'ボツワナ' },
  { code: 'BV', name_en: 'Bouvet Island', name_ja: 'ブーベ島' },
  { code: 'BR', name_en: 'Brazil', name_ja: 'ブラジル' },
  {
    code: 'IO',
    name_en: 'British Indian Ocean Territory',
    name_ja: 'イギリス領インド洋地域',
  },
  {
    code: 'BN',
    name_en: 'Brunei Darussalam',
    name_ja: 'ブルネイ・ダルサラーム',
  },
  { code: 'BG', name_en: 'Bulgaria', name_ja: 'ブルガリア' },
  { code: 'BF', name_en: 'Burkina Faso', name_ja: 'ブルキナファソ' },
  { code: 'BI', name_en: 'Burundi', name_ja: 'ブルンジ' },
  { code: 'KH', name_en: 'Cambodia', name_ja: 'カンボジア' },
  { code: 'CM', name_en: 'Cameroon', name_ja: 'カメルーン' },
  { code: 'CA', name_en: 'Canada', name_ja: 'カナダ' },
  { code: 'CV', name_en: 'Cape Verde', name_ja: 'カーボベルデ' },
  { code: 'KY', name_en: 'Cayman Islands', name_ja: 'ケイマン諸島' },
  {
    code: 'CF',
    name_en: 'Central African Republic',
    name_ja: '中央アフリカ共和国',
  },
  { code: 'TD', name_en: 'Chad', name_ja: 'チャド' },
  { code: 'CL', name_en: 'Chile', name_ja: 'チリ' },
  { code: 'CN', name_en: 'China', name_ja: '中国' },
  { code: 'CX', name_en: 'Christmas Island', name_ja: 'クリスマス島' },
  {
    code: 'CC',
    name_en: 'Cocos (Keeling) Islands',
    name_ja: 'ココス（キーリング）諸島',
  },
  { code: 'CO', name_en: 'Colombia', name_ja: 'コロンビア' },
  { code: 'KM', name_en: 'Comoros', name_ja: 'コモロ' },
  { code: 'CG', name_en: 'Congo', name_ja: 'コンゴ' },
  {
    code: 'CD',
    name_en: 'Congo, Democratic Republic',
    name_ja: 'コンゴ民主共和国',
  },
  { code: 'CK', name_en: 'Cook Islands', name_ja: 'クック諸島' },
  { code: 'CR', name_en: 'Costa Rica', name_ja: 'コスタリカ' },
  { code: 'CI', name_en: "Cote D'Ivoire", name_ja: 'コートジボワール' },
  { code: 'HR', name_en: 'Croatia', name_ja: 'クロアチア' },
  { code: 'CU', name_en: 'Cuba', name_ja: 'キューバ' },
  { code: 'CY', name_en: 'Cyprus', name_ja: 'キプロス' },
  { code: 'CZ', name_en: 'Czech Republic', name_ja: 'チェコ共和国' },
  { code: 'DK', name_en: 'Denmark', name_ja: 'デンマーク' },
  { code: 'DJ', name_en: 'Djibouti', name_ja: 'ジブチ' },
  { code: 'DM', name_en: 'Dominica', name_ja: 'ドミニカ国' },
  { code: 'DO', name_en: 'Dominican Republic', name_ja: 'ドミニカ共和国' },
  { code: 'EC', name_en: 'Ecuador', name_ja: 'エクアドル' },
  { code: 'EG', name_en: 'Egypt', name_ja: 'エジプト' },
  { code: 'SV', name_en: 'El Salvador', name_ja: 'エルサルバドル' },
  { code: 'GQ', name_en: 'Equatorial Guinea', name_ja: '赤道ギニア' },
  { code: 'ER', name_en: 'Eritrea', name_ja: 'エリトリア' },
  { code: 'EE', name_en: 'Estonia', name_ja: 'エストニア' },
  { code: 'ET', name_en: 'Ethiopia', name_ja: 'エチオピア' },
  {
    code: 'FK',
    name_en: 'Falkland Islands (Malvinas)',
    name_ja: 'フォークランド（マルビナス）諸島',
  },
  { code: 'FO', name_en: 'Faroe Islands', name_ja: 'フェロー諸島' },
  { code: 'FJ', name_en: 'Fiji', name_ja: 'フィジー' },
  { code: 'FI', name_en: 'Finland', name_ja: 'フィンランド' },
  { code: 'FR', name_en: 'France', name_ja: 'フランス' },
  { code: 'GF', name_en: 'French Guiana', name_ja: 'フランス領ギアナ' },
  { code: 'PF', name_en: 'French Polynesia', name_ja: 'フランス領ポリネシア' },
  {
    code: 'TF',
    name_en: 'French Southern Territories',
    name_ja: 'フランス領南方・南極地域',
  },
  { code: 'GA', name_en: 'Gabon', name_ja: 'ガボン' },
  { code: 'GM', name_en: 'Gambia', name_ja: 'ガンビア' },
  { code: 'GE', name_en: 'Georgia', name_ja: 'ジョージア（グルジア）' },
  { code: 'DE', name_en: 'Germany', name_ja: 'ドイツ' },
  { code: 'GH', name_en: 'Ghana', name_ja: 'ガーナ' },
  { code: 'GI', name_en: 'Gibraltar', name_ja: 'ジブラルタル' },
  { code: 'GR', name_en: 'Greece', name_ja: 'ギリシャ' },
  { code: 'GL', name_en: 'Greenland', name_ja: 'グリーンランド' },
  { code: 'GD', name_en: 'Grenada', name_ja: 'グレナダ' },
  { code: 'GP', name_en: 'Guadeloupe', name_ja: 'グアドループ' },
  { code: 'GU', name_en: 'Guam', name_ja: 'グアム' },
  { code: 'GT', name_en: 'Guatemala', name_ja: 'グアテマラ' },
  { code: 'GG', name_en: 'Guernsey', name_ja: 'ガーンジー' },
  { code: 'GN', name_en: 'Guinea', name_ja: 'ギニア' },
  { code: 'GW', name_en: 'Guinea-Bissau', name_ja: 'ギニアビサウ' },
  { code: 'GY', name_en: 'Guyana', name_ja: 'ガイアナ' },
  { code: 'HT', name_en: 'Haiti', name_ja: 'ハイチ' },
  {
    code: 'HM',
    name_en: 'Heard Island & Mcdonald Islands',
    name_ja: 'ハード島・マクドナルド諸島',
  },
  {
    code: 'VA',
    name_en: 'Holy See (Vatican City State)',
    name_ja: 'ローマ教皇庁（バチカン市国）',
  },
  { code: 'HN', name_en: 'Honduras', name_ja: 'ホンジュラス' },
  { code: 'HK', name_en: 'Hong Kong', name_ja: '香港' },
  { code: 'HU', name_en: 'Hungary', name_ja: 'ハンガリー' },
  { code: 'IS', name_en: 'Iceland', name_ja: 'アイスランド' },
  { code: 'IN', name_en: 'India', name_ja: 'インド' },
  { code: 'ID', name_en: 'Indonesia', name_ja: 'インドネシア' },
  {
    code: 'IR',
    name_en: 'Iran, Islamic Republic Of',
    name_ja: 'イラン・イスラム共和国',
  },
  { code: 'IQ', name_en: 'Iraq', name_ja: 'イラク' },
  { code: 'IE', name_en: 'Ireland', name_ja: 'アイルランド' },
  { code: 'IM', name_en: 'Isle Of Man', name_ja: 'マン島' },
  { code: 'IL', name_en: 'Israel', name_ja: 'イスラエル' },
  { code: 'IT', name_en: 'Italy', name_ja: 'イタリア' },
  { code: 'JM', name_en: 'Jamaica', name_ja: 'ジャマイカ' },
  { code: 'JP', name_en: 'Japan', name_ja: '日本' },
  { code: 'JE', name_en: 'Jersey', name_ja: 'ジャージー' },
  { code: 'JO', name_en: 'Jordan', name_ja: 'ヨルダン' },
  { code: 'KZ', name_en: 'Kazakhstan', name_ja: 'カザフスタン' },
  { code: 'KE', name_en: 'Kenya', name_ja: 'ケニア' },
  { code: 'KI', name_en: 'Kiribati', name_ja: 'キリバス' },
  { code: 'KR', name_en: 'Korea', name_ja: '韓国' },
  { code: 'KW', name_en: 'Kuwait', name_ja: 'クウェート' },
  { code: 'KG', name_en: 'Kyrgyzstan', name_ja: 'キルギス' },
  {
    code: 'LA',
    name_en: "Lao People's Democratic Republic",
    name_ja: 'ラオス人民民主共和国',
  },
  { code: 'LV', name_en: 'Latvia', name_ja: 'ラトビア' },
  { code: 'LB', name_en: 'Lebanon', name_ja: 'レバノン' },
  { code: 'LS', name_en: 'Lesotho', name_ja: 'レソト' },
  { code: 'LR', name_en: 'Liberia', name_ja: 'リベリア' },
  {
    code: 'LY',
    name_en: 'Libyan Arab Jamahiriya',
    name_ja: 'リビア・アラブ・ジャマーヒリーヤ国',
  },
  { code: 'LI', name_en: 'Liechtenstein', name_ja: 'リヒテンシュタイン' },
  { code: 'LT', name_en: 'Lithuania', name_ja: 'リトアニア' },
  { code: 'LU', name_en: 'Luxembourg', name_ja: 'ルクセンブルク' },
  { code: 'MO', name_en: 'Macao', name_ja: 'マカオ' },
  { code: 'MK', name_en: 'North Macedonia', name_ja: '北マケドニア' },
  { code: 'MG', name_en: 'Madagascar', name_ja: 'マダガスカル' },
  { code: 'MW', name_en: 'Malawi', name_ja: 'マラウイ' },
  { code: 'MY', name_en: 'Malaysia', name_ja: 'マレーシア' },
  { code: 'MV', name_en: 'Maldives', name_ja: 'モルディブ' },
  { code: 'ML', name_en: 'Mali', name_ja: 'マリ' },
  { code: 'MT', name_en: 'Malta', name_ja: 'マルタ' },
  { code: 'MH', name_en: 'Marshall Islands', name_ja: 'マーシャル諸島' },
  { code: 'MQ', name_en: 'Martinique', name_ja: 'マルティニーク' },
  { code: 'MR', name_en: 'Mauritania', name_ja: 'モーリタニア' },
  { code: 'MU', name_en: 'Mauritius', name_ja: 'モーリシャス' },
  { code: 'YT', name_en: 'Mayotte', name_ja: 'マヨット' },
  { code: 'MX', name_en: 'Mexico', name_ja: 'メキシコ' },
  {
    code: 'FM',
    name_en: 'Micronesia, Federated States Of',
    name_ja: 'ミクロネシア連邦',
  },
  { code: 'MD', name_en: 'Moldova', name_ja: 'モルドバ' },
  { code: 'MC', name_en: 'Monaco', name_ja: 'モナコ' },
  { code: 'MN', name_en: 'Mongolia', name_ja: 'モンゴル' },
  { code: 'ME', name_en: 'Montenegro', name_ja: 'モンテネグロ' },
  { code: 'MS', name_en: 'Montserrat', name_ja: 'モントセラト' },
  { code: 'MA', name_en: 'Morocco', name_ja: 'モロッコ' },
  { code: 'MZ', name_en: 'Mozambique', name_ja: 'モザンビーク' },
  { code: 'MM', name_en: 'Myanmar', name_ja: 'ミャンマー' },
  { code: 'NA', name_en: 'Namibia', name_ja: 'ナミビア' },
  { code: 'NR', name_en: 'Nauru', name_ja: 'ナウル' },
  { code: 'NP', name_en: 'Nepal', name_ja: 'ネパール' },
  { code: 'NL', name_en: 'Netherlands', name_ja: 'オランダ' },
  {
    code: 'AN',
    name_en: 'Netherlands Antilles',
    name_ja: 'オランダ領アンティル',
  },
  { code: 'NC', name_en: 'New Caledonia', name_ja: 'ニューカレドニア' },
  { code: 'NZ', name_en: 'New Zealand', name_ja: 'ニュージーランド' },
  { code: 'NI', name_en: 'Nicaragua', name_ja: 'ニカラグア' },
  { code: 'NE', name_en: 'Niger', name_ja: 'ニジェール' },
  { code: 'NG', name_en: 'Nigeria', name_ja: 'ナイジェリア' },
  { code: 'NU', name_en: 'Niue', name_ja: 'ニウエ' },
  { code: 'NF', name_en: 'Norfolk Island', name_ja: 'ノーフォーク島' },
  {
    code: 'MP',
    name_en: 'Northern Mariana Islands',
    name_ja: '北マリアナ諸島',
  },
  { code: 'NO', name_en: 'Norway', name_ja: 'ノルウェー' },
  { code: 'OM', name_en: 'Oman', name_ja: 'オマーン' },
  { code: 'PK', name_en: 'Pakistan', name_ja: 'パキスタン' },
  { code: 'PW', name_en: 'Palau', name_ja: 'パラオ' },
  {
    code: 'PS',
    name_en: 'Palestinian Territory, Occupied',
    name_ja: 'パレスチナ自治区',
  },
  { code: 'PA', name_en: 'Panama', name_ja: 'パナマ' },
  { code: 'PG', name_en: 'Papua New Guinea', name_ja: 'パプアニューギニア' },
  { code: 'PY', name_en: 'Paraguay', name_ja: 'パラグアイ' },
  { code: 'PE', name_en: 'Peru', name_ja: 'ペルー' },
  { code: 'PH', name_en: 'Philippines', name_ja: 'フィリピン' },
  { code: 'PN', name_en: 'Pitcairn', name_ja: 'ピトケアン' },
  { code: 'PL', name_en: 'Poland', name_ja: 'ポーランド' },
  { code: 'PT', name_en: 'Portugal', name_ja: 'ポルトガル' },
  { code: 'PR', name_en: 'Puerto Rico', name_ja: 'プエルトリコ' },
  { code: 'QA', name_en: 'Qatar', name_ja: 'カタール' },
  { code: 'RE', name_en: 'Reunion', name_ja: 'レユニオン' },
  { code: 'RO', name_en: 'Romania', name_ja: 'ルーマニア' },
  { code: 'RU', name_en: 'Russian Federation', name_ja: 'ロシア連邦' },
  { code: 'RW', name_en: 'Rwanda', name_ja: 'ルワンダ' },
  { code: 'BL', name_en: 'Saint Barthelemy', name_ja: 'サン・バルテルミー' },
  { code: 'SH', name_en: 'Saint Helena', name_ja: 'セントヘレナ' },
  {
    code: 'KN',
    name_en: 'Saint Kitts And Nevis',
    name_ja: 'セントクリストファー・ネーヴィス',
  },
  { code: 'LC', name_en: 'Saint Lucia', name_ja: 'セントルシア' },
  { code: 'MF', name_en: 'Saint Martin', name_ja: 'サン・マルタン' },
  {
    code: 'PM',
    name_en: 'Saint Pierre And Miquelon',
    name_ja: 'サンピエール島・ミクロン島',
  },
  {
    code: 'VC',
    name_en: 'Saint Vincent And Grenadines',
    name_ja: 'セントビンセントおよびグレナディーン諸島',
  },
  { code: 'WS', name_en: 'Samoa', name_ja: 'サモア' },
  { code: 'SM', name_en: 'San Marino', name_ja: 'サンマリノ' },
  {
    code: 'ST',
    name_en: 'Sao Tome And Principe',
    name_ja: 'サントメ・プリンシペ',
  },
  { code: 'SA', name_en: 'Saudi Arabia', name_ja: 'サウジアラビア' },
  { code: 'SN', name_en: 'Senegal', name_ja: 'セネガル' },
  { code: 'RS', name_en: 'Serbia', name_ja: 'セルビア' },
  { code: 'SC', name_en: 'Seychelles', name_ja: 'セーシェル' },
  { code: 'SL', name_en: 'Sierra Leone', name_ja: 'シエラレオネ' },
  { code: 'SG', name_en: 'Singapore', name_ja: 'シンガポール' },
  { code: 'SK', name_en: 'Slovakia', name_ja: 'スロバキア' },
  { code: 'SI', name_en: 'Slovenia', name_ja: 'スロベニア' },
  { code: 'SB', name_en: 'Solomon Islands', name_ja: 'ソロモン諸島' },
  { code: 'SO', name_en: 'Somalia', name_ja: 'ソマリア' },
  { code: 'ZA', name_en: 'South Africa', name_ja: '南アフリカ' },
  {
    code: 'GS',
    name_en: 'South Georgia And Sandwich Isl.',
    name_ja: 'サウスジョージア・サウスサンドウィッチ諸島',
  },
  { code: 'ES', name_en: 'Spain', name_ja: 'スペイン' },
  { code: 'LK', name_en: 'Sri Lanka', name_ja: 'スリランカ' },
  { code: 'SD', name_en: 'Sudan', name_ja: 'スーダン' },
  { code: 'SR', name_en: 'Suriname', name_ja: 'スリナム' },
  {
    code: 'SJ',
    name_en: 'Svalbard And Jan Mayen',
    name_ja: 'スヴァールバル諸島およびヤンマイエン島',
  },
  { code: 'SZ', name_en: 'Swaziland', name_ja: 'スワジランド' },
  { code: 'SE', name_en: 'Sweden', name_ja: 'スウェーデン' },
  { code: 'CH', name_en: 'Switzerland', name_ja: 'スイス' },
  {
    code: 'SY',
    name_en: 'Syrian Arab Republic',
    name_ja: 'シリア・アラブ共和国',
  },
  { code: 'TW', name_en: 'Taiwan', name_ja: '台湾' },
  { code: 'TJ', name_en: 'Tajikistan', name_ja: 'タジキスタン' },
  { code: 'TZ', name_en: 'Tanzania', name_ja: 'タンザニア' },
  { code: 'TH', name_en: 'Thailand', name_ja: 'タイ' },
  { code: 'TL', name_en: 'Timor-Leste', name_ja: '東ティモール' },
  { code: 'TG', name_en: 'Togo', name_ja: 'トーゴ' },
  { code: 'TK', name_en: 'Tokelau', name_ja: 'トケラウ' },
  { code: 'TO', name_en: 'Tonga', name_ja: 'トンガ' },
  {
    code: 'TT',
    name_en: 'Trinidad And Tobago',
    name_ja: 'トリニダード・トバゴ',
  },
  { code: 'TN', name_en: 'Tunisia', name_ja: 'チュニジア' },
  { code: 'TR', name_en: 'Turkey', name_ja: 'トルコ' },
  { code: 'TM', name_en: 'Turkmenistan', name_ja: 'トルクメニスタン' },
  {
    code: 'TC',
    name_en: 'Turks And Caicos Islands',
    name_ja: 'タークス・カイコス諸島',
  },
  { code: 'TV', name_en: 'Tuvalu', name_ja: 'ツバル' },
  { code: 'UG', name_en: 'Uganda', name_ja: 'ウガンダ' },
  { code: 'UA', name_en: 'Ukraine', name_ja: 'ウクライナ' },
  { code: 'AE', name_en: 'United Arab Emirates', name_ja: 'アラブ首長国連邦' },
  { code: 'GB', name_en: 'United Kingdom', name_ja: 'イギリス' },
  { code: 'US', name_en: 'United States', name_ja: 'アメリカ合衆国' },
  {
    code: 'UM',
    name_en: 'United States Outlying Islands',
    name_ja: '合衆国領有小離島',
  },
  { code: 'UY', name_en: 'Uruguay', name_ja: 'ウルグアイ' },
  { code: 'UZ', name_en: 'Uzbekistan', name_ja: 'ウズベキスタン' },
  { code: 'VU', name_en: 'Vanuatu', name_ja: 'バヌアツ' },
  { code: 'VE', name_en: 'Venezuela', name_ja: 'ベネズエラ' },
  { code: 'VN', name_en: 'Viet Nam', name_ja: 'ベトナム' },
  {
    code: 'VG',
    name_en: 'Virgin Islands, British',
    name_ja: 'イギリス領ヴァージン諸島',
  },
  {
    code: 'VI',
    name_en: 'Virgin Islands, U.S.',
    name_ja: 'アメリカ領ヴァージン諸島',
  },
  { code: 'WF', name_en: 'Wallis And Futuna', name_ja: 'ウォリス・フツナ' },
  { code: 'EH', name_en: 'Western Sahara', name_ja: '西サハラ' },
  { code: 'YE', name_en: 'Yemen', name_ja: 'イエメン' },
  { code: 'ZM', name_en: 'Zambia', name_ja: 'ザンビア' },
  { code: 'ZW', name_en: 'Zimbabwe', name_ja: 'ジンバブエ' },
];

export const isValidCountryCode = (code: string): boolean =>
  /^[A-Z]{2}$/.test(code);

export const countryOptions = (locale: string) => {
  const nameKey = `name_${locale}` as `name_${string}`;
  const fallbackKey: `name_${string}` = 'name_en';

  return countries.map((country) => ({
    label: country[nameKey] ?? country[fallbackKey],
    value: country.code,
  }));
};
