type Language = {
  code: string;
  [key: `name_${string}`]: string;
};

export const languages: Language[] = [
  { code: 'aa', name_en: 'Afar', name_ja: 'アファル語' },
  { code: 'ab', name_en: 'Abkhazian', name_ja: 'アブハズ語' },
  { code: 'ae', name_en: 'Avestan', name_ja: 'アヴェスター語' },
  { code: 'af', name_en: 'Afrikaans', name_ja: 'アフリカーンス語' },
  { code: 'ak', name_en: 'Akan', name_ja: 'アカン語' },
  { code: 'am', name_en: 'Amharic', name_ja: 'アムハラ語' },
  { code: 'an', name_en: 'Aragonese', name_ja: 'アラゴン語' },
  { code: 'ar', name_en: 'Arabic', name_ja: 'アラビア語' },
  { code: 'as', name_en: 'Assamese', name_ja: 'アッサム語' },
  { code: 'av', name_en: 'Avaric', name_ja: 'アヴァル語' },
  { code: 'ay', name_en: 'Aymara', name_ja: 'アイマラ語' },
  { code: 'az', name_en: 'Azerbaijani', name_ja: 'アゼルバイジャン語' },
  { code: 'ba', name_en: 'Bashkir', name_ja: 'バシキール語' },
  { code: 'be', name_en: 'Belarusian', name_ja: 'ベラルーシ語' },
  { code: 'bg', name_en: 'Bulgarian', name_ja: 'ブルガリア語' },
  { code: 'bh', name_en: 'Bihari', name_ja: 'ビハール語' },
  { code: 'bi', name_en: 'Bislama', name_ja: 'ビスラマ語' },
  { code: 'bm', name_en: 'Bambara', name_ja: 'バンバラ語' },
  { code: 'bn', name_en: 'Bengali', name_ja: 'ベンガル語' },
  { code: 'bo', name_en: 'Tibetan', name_ja: 'チベット語' },
  { code: 'br', name_en: 'Breton', name_ja: 'ブルトン語' },
  { code: 'bs', name_en: 'Bosnian', name_ja: 'ボスニア語' },
  { code: 'ca', name_en: 'Catalan', name_ja: 'カタルーニャ語' },
  { code: 'ce', name_en: 'Chechen', name_ja: 'チェチェン語' },
  { code: 'ch', name_en: 'Chamorro', name_ja: 'チャモロ語' },
  { code: 'co', name_en: 'Corsican', name_ja: 'コルシカ語' },
  { code: 'cr', name_en: 'Cree', name_ja: 'クリー語' },
  { code: 'cs', name_en: 'Czech', name_ja: 'チェコ語' },
  { code: 'cu', name_en: 'Old Church Slavonic', name_ja: '古代教会スラヴ語' },
  { code: 'cv', name_en: 'Chuvash', name_ja: 'チュヴァシ語' },
  { code: 'cy', name_en: 'Welsh', name_ja: 'ウェールズ語' },
  { code: 'da', name_en: 'Danish', name_ja: 'デンマーク語' },
  { code: 'de', name_en: 'German', name_ja: 'ドイツ語' },
  { code: 'dv', name_en: 'Divehi', name_ja: 'ディベヒ語' },
  { code: 'dz', name_en: 'Dzongkha', name_ja: 'ゾンカ語' },
  { code: 'ee', name_en: 'Ewe', name_ja: 'エウェ語' },
  { code: 'el', name_en: 'Greek', name_ja: 'ギリシャ語' },
  { code: 'en', name_en: 'English', name_ja: '英語' },
  { code: 'eo', name_en: 'Esperanto', name_ja: 'エスペラント' },
  { code: 'es', name_en: 'Spanish', name_ja: 'スペイン語' },
  { code: 'et', name_en: 'Estonian', name_ja: 'エストニア語' },
  { code: 'eu', name_en: 'Basque', name_ja: 'バスク語' },
  { code: 'fa', name_en: 'Persian', name_ja: 'ペルシア語' },
  { code: 'ff', name_en: 'Fula', name_ja: 'フラ語' },
  { code: 'fi', name_en: 'Finnish', name_ja: 'フィンランド語' },
  { code: 'fj', name_en: 'Fijian', name_ja: 'フィジー語' },
  { code: 'fo', name_en: 'Faroese', name_ja: 'フェロー語' },
  { code: 'fr', name_en: 'French', name_ja: 'フランス語' },
  { code: 'fy', name_en: 'Frisian', name_ja: 'フリジア語' },
  { code: 'ga', name_en: 'Irish', name_ja: 'アイルランド語' },
  {
    code: 'gd',
    name_en: 'Gaelic (Scottish)',
    name_ja: 'スコットランド・ゲール語',
  },
  { code: 'gl', name_en: 'Galician', name_ja: 'ガリシア語' },
  { code: 'gn', name_en: 'Guarani', name_ja: 'グアラニー語' },
  { code: 'gu', name_en: 'Gujarati', name_ja: 'グジャラート語' },
  { code: 'gv', name_en: 'Manx', name_ja: 'マン島語' },
  { code: 'ha', name_en: 'Hausa', name_ja: 'ハウサ語' },
  { code: 'he', name_en: 'Hebrew', name_ja: 'ヘブライ語' },
  { code: 'hi', name_en: 'Hindi', name_ja: 'ヒンディー語' },
  { code: 'ho', name_en: 'Hiri Motu', name_ja: 'ヒリモトゥ語' },
  { code: 'hr', name_en: 'Croatian', name_ja: 'クロアチア語' },
  { code: 'ht', name_en: 'Haitian', name_ja: 'ハイチ語' },
  { code: 'hu', name_en: 'Hungarian', name_ja: 'ハンガリー語' },
  { code: 'hy', name_en: 'Armenian', name_ja: 'アルメニア語' },
  { code: 'hz', name_en: 'Herero', name_ja: 'ヘレロ語' },
  { code: 'ia', name_en: 'Interlingua', name_ja: 'インターリングア' },
  { code: 'id', name_en: 'Indonesian', name_ja: 'インドネシア語' },
  { code: 'ie', name_en: 'Interlingue', name_ja: 'インターリング' },
  { code: 'ig', name_en: 'Igbo', name_ja: 'イボ語' },
  { code: 'ii', name_en: 'Sichuan Yi', name_ja: '四川彝語' },
  { code: 'ik', name_en: 'Inupiaq', name_ja: 'イヌピアック語' },
  { code: 'io', name_en: 'Ido', name_ja: 'イド語' },
  { code: 'is', name_en: 'Icelandic', name_ja: 'アイスランド語' },
  { code: 'it', name_en: 'Italian', name_ja: 'イタリア語' },
  { code: 'iu', name_en: 'Inuktitut', name_ja: 'イヌクティトゥット語' },
  { code: 'ja', name_en: 'Japanese', name_ja: '日本語' },
  { code: 'jv', name_en: 'Javanese', name_ja: 'ジャワ語' },
  { code: 'ka', name_en: 'Georgian', name_ja: 'グルジア語' },
  { code: 'kg', name_en: 'Kongo', name_ja: 'コンゴ語' },
  { code: 'ki', name_en: 'Kikuyu', name_ja: 'キクユ語' },
  { code: 'kj', name_en: 'Kuanyama', name_ja: 'クワニャマ語' },
  { code: 'kk', name_en: 'Kazakh', name_ja: 'カザフ語' },
  { code: 'kl', name_en: 'Kalaallisut', name_ja: 'グリーンランド語' },
  { code: 'km', name_en: 'Khmer', name_ja: 'クメール語' },
  { code: 'kn', name_en: 'Kannada', name_ja: 'カンナダ語' },
  { code: 'ko', name_en: 'Korean', name_ja: '韓国語/朝鮮語' },
  { code: 'kr', name_en: 'Kanuri', name_ja: 'カヌリ語' },
  { code: 'ks', name_en: 'Kashmiri', name_ja: 'カシミール語' },
  { code: 'ku', name_en: 'Kurdish', name_ja: 'クルド語' },
  { code: 'kv', name_en: 'Komi', name_ja: 'コミ語' },
  { code: 'kw', name_en: 'Cornish', name_ja: 'コーンウォール語' },
  { code: 'ky', name_en: 'Kirghiz', name_ja: 'キルギス語' },
  { code: 'la', name_en: 'Latin', name_ja: 'ラテン語' },
  { code: 'lb', name_en: 'Luxembourgish', name_ja: 'ルクセンブルク語' },
  { code: 'lg', name_en: 'Ganda', name_ja: 'ガンダ語' },
  { code: 'li', name_en: 'Limburgish', name_ja: 'リンブルフ語' },
  { code: 'ln', name_en: 'Lingala', name_ja: 'リンガラ語' },
  { code: 'lo', name_en: 'Lao', name_ja: 'ラオ語' },
  { code: 'lt', name_en: 'Lithuanian', name_ja: 'リトアニア語' },
  { code: 'lu', name_en: 'Luba-Katanga', name_ja: 'ルバ・カタンガ語' },
  { code: 'lv', name_en: 'Latvian', name_ja: 'ラトビア語' },
  { code: 'mg', name_en: 'Malagasy', name_ja: 'マダガスカル語' },
  { code: 'mh', name_en: 'Marshallese', name_ja: 'マーシャル語' },
  { code: 'mi', name_en: 'Maori', name_ja: 'マオリ語' },
  { code: 'mk', name_en: 'Macedonian', name_ja: 'マケドニア語' },
  { code: 'ml', name_en: 'Malayalam', name_ja: 'マラヤーラム語' },
  { code: 'mn', name_en: 'Mongolian', name_ja: 'モンゴル語' },
  { code: 'mr', name_en: 'Marathi', name_ja: 'マラーティー語' },
  { code: 'ms', name_en: 'Malay', name_ja: 'マレー語' },
  { code: 'mt', name_en: 'Maltese', name_ja: 'マルタ語' },
  { code: 'my', name_en: 'Burmese', name_ja: 'ビルマ語' },
  { code: 'na', name_en: 'Nauru', name_ja: 'ナウル語' },
  {
    code: 'nb',
    name_en: 'Norwegian Bokmål',
    name_ja: 'ノルウェー語ブークモール',
  },
  { code: 'nd', name_en: 'Ndebele, North', name_ja: '北ンデベレ語' },
  { code: 'ne', name_en: 'Nepali', name_ja: 'ネパール語' },
  { code: 'ng', name_en: 'Ndonga', name_ja: 'ンドンガ語' },
  { code: 'nl', name_en: 'Dutch', name_ja: 'オランダ語' },
  {
    code: 'nn',
    name_en: 'Norwegian Nynorsk',
    name_ja: 'ノルウェー語ニーノシュク',
  },
  { code: 'no', name_en: 'Norwegian', name_ja: 'ノルウェー語' },
  { code: 'nr', name_en: 'Ndebele, South', name_ja: '南ンデベレ語' },
  { code: 'nv', name_en: 'Navajo', name_ja: 'ナバホ語' },
  { code: 'ny', name_en: 'Chichewa', name_ja: 'チェワ語' },
  { code: 'oc', name_en: 'Occitan', name_ja: 'オック語' },
  { code: 'oj', name_en: 'Ojibwa', name_ja: 'オジブウェー語' },
  { code: 'om', name_en: 'Oromo', name_ja: 'オロモ語' },
  { code: 'or', name_en: 'Oriya', name_ja: 'オリヤー語' },
  { code: 'os', name_en: 'Ossetian', name_ja: 'オセチア語' },
  { code: 'pa', name_en: 'Panjabi', name_ja: 'パンジャブ語' },
  { code: 'pi', name_en: 'Pali', name_ja: 'パーリ語' },
  { code: 'pl', name_en: 'Polish', name_ja: 'ポーランド語' },
  { code: 'ps', name_en: 'Pushto', name_ja: 'パシュトー語' },
  { code: 'pt', name_en: 'Portuguese', name_ja: 'ポルトガル語' },
  { code: 'qu', name_en: 'Quechua', name_ja: 'ケチュア語' },
  { code: 'rm', name_en: 'Romansh', name_ja: 'ロマンシュ語' },
  { code: 'rn', name_en: 'Rundi', name_ja: 'ルンディ語' },
  { code: 'ro', name_en: 'Romanian', name_ja: 'ルーマニア語' },
  { code: 'ru', name_en: 'Russian', name_ja: 'ロシア語' },
  { code: 'rw', name_en: 'Kinyarwanda', name_ja: 'ルワンダ語' },
  { code: 'sa', name_en: 'Sanskrit', name_ja: 'サンスクリット' },
  { code: 'sc', name_en: 'Sardinian', name_ja: 'サルデーニャ語' },
  { code: 'sd', name_en: 'Sindhi', name_ja: 'シンド語' },
  { code: 'se', name_en: 'Northern Sami', name_ja: '北サーミ語' },
  { code: 'sg', name_en: 'Sango', name_ja: 'サンゴ語' },
  { code: 'si', name_en: 'Sinhala', name_ja: 'シンハラ語' },
  { code: 'sk', name_en: 'Slovak', name_ja: 'スロバキア語' },
  { code: 'sl', name_en: 'Slovenian', name_ja: 'スロベニア語' },
  { code: 'sm', name_en: 'Samoan', name_ja: 'サモア語' },
  { code: 'sn', name_en: 'Shona', name_ja: 'ショナ語' },
  { code: 'so', name_en: 'Somali', name_ja: 'ソマリ語' },
  { code: 'sq', name_en: 'Albanian', name_ja: 'アルバニア語' },
  { code: 'sr', name_en: 'Serbian', name_ja: 'セルビア語' },
  { code: 'ss', name_en: 'Swati', name_ja: 'スワティ語' },
  { code: 'st', name_en: 'Sotho, Southern', name_ja: '南ソト語' },
  { code: 'su', name_en: 'Sundanese', name_ja: 'スンダ語' },
  { code: 'sv', name_en: 'Swedish', name_ja: 'スウェーデン語' },
  { code: 'sw', name_en: 'Swahili', name_ja: 'スワヒリ語' },
  { code: 'ta', name_en: 'Tamil', name_ja: 'タミル語' },
  { code: 'te', name_en: 'Telugu', name_ja: 'テルグ語' },
  { code: 'tg', name_en: 'Tajik', name_ja: 'タジク語' },
  { code: 'th', name_en: 'Thai', name_ja: 'タイ語' },
  { code: 'ti', name_en: 'Tigrinya', name_ja: 'ティグリニャ語' },
  { code: 'tk', name_en: 'Turkmen', name_ja: 'トルクメン語' },
  { code: 'tl', name_en: 'Tagalog', name_ja: 'タガログ語' },
  { code: 'tn', name_en: 'Tswana', name_ja: 'ツワナ語' },
  { code: 'to', name_en: 'Tonga (Tonga Islands)', name_ja: 'トンガ語' },
  { code: 'tr', name_en: 'Turkish', name_ja: 'トルコ語' },
  { code: 'ts', name_en: 'Tsonga', name_ja: 'ツォンガ語' },
  { code: 'tt', name_en: 'Tatar', name_ja: 'タタール語' },
  { code: 'tw', name_en: 'Twi', name_ja: 'トウィ語' },
  { code: 'ty', name_en: 'Tahitian', name_ja: 'タヒチ語' },
  { code: 'ug', name_en: 'Uighur', name_ja: 'ウイグル語' },
  { code: 'uk', name_en: 'Ukrainian', name_ja: 'ウクライナ語' },
  { code: 'ur', name_en: 'Urdu', name_ja: 'ウルドゥー語' },
  { code: 'uz', name_en: 'Uzbek', name_ja: 'ウズベク語' },
  { code: 've', name_en: 'Venda', name_ja: 'ヴェンダ語' },
  { code: 'vi', name_en: 'Vietnamese', name_ja: 'ベトナム語' },
  { code: 'vo', name_en: 'Volapük', name_ja: 'ヴォラピュク語' },
  { code: 'wa', name_en: 'Walloon', name_ja: 'ワロン語' },
  { code: 'wo', name_en: 'Wolof', name_ja: 'ウォロフ語' },
  { code: 'xh', name_en: 'Xhosa', name_ja: 'コサ語' },
  { code: 'yi', name_en: 'Yiddish', name_ja: 'イディッシュ語' },
  { code: 'yo', name_en: 'Yoruba', name_ja: 'ヨルバ語' },
  { code: 'za', name_en: 'Zhuang', name_ja: 'チワン語' },
  { code: 'zh', name_en: 'Chinese', name_ja: '中国語' },
  { code: 'zu', name_en: 'Zulu', name_ja: 'ズールー語' },
];

type LanguageOption = { label: string; value: string };

const getLocalizedName = (item: Language, locale: string): string => {
  const nameKey = `name_${locale}` as `name_${string}`;
  return item[nameKey] ?? item.name_en;
};

export const languageOptions = (locale: string): LanguageOption[] => {
  return languages
    .map((lang) => ({
      label: getLocalizedName(lang, locale),
      value: lang.code,
    }))
    .sort((a, b) => a.label.localeCompare(b.label));
};
